export const data = {
	'222': {
		name: 'Emerald-Denver',
		pretitle: 'United Kingdoms',
		flag: 'https://i.postimg.cc/Dzqrs3Rs/Union-Flag.png',
		formation: '1980',
		population: 42300000,
		birthright: 'Unconditional',
		languages: 'Cimbrian, Ludvillian, Colradian',
		governmentType: 'Unitary Constitutional Monarchy/Confederation',
		powerSource: 'Democracy',
		ideology: 'Socialist',
		legislature: {
			name: 'Congress',
			upper: 'Union Senate',
			lower: 'Union House Of Representatives'
		},
		militarySpending: 8,
		conscription: 'Yes, a minority of the age groups is drafted',
		nuclearWeapons: 'Inactive',
		chemicalWeapons: 'Inactive',
		biologicalWeapons: 'No',
		currency: 'Emeraldian Buck',
		gdp: 950546650000,
		industries: 'Cars, Planes, and Guns',
		oil: 'Does not produce oil',
		coal: 'Does not mine coal',
		lifeExpectancy: null,
		mys: null,
		eys: null,
		GNIpc: 23206,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Abolished',
		torture: 'Illegal',
		capitalPunishment: 'Legal',
		sameSexMarriage: 'Legal',
		prostitution: 'Illegal',
		laneSplitting: 'Illegal',
		internetAccess: 'Yes',
		drugs: 'Certain substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: '',
		speedLimit: '100 km/h',
		drivingSide: 'Right',
		area: 79301
	},
	'033': {
		name: 'Esfalsa',
		pretitle: '',
		flag: 'https://raw.githubusercontent.com/esfalsagov/esfalsa-graphics/main/flag%20of%20esfalsa.svg',
		formation: '1043',
		population: 18793005,
		birthright: 'Restrictive birthright',
		languages: 'Austral',
		governmentType: 'Unitary presidential directorial republic',
		powerSource: 'Democracy',
		ideology: 'Liberal',
		legislature: {
			name: 'Assembly',
			upper: '',
			lower: ''
		},
		militarySpending: 2.3,
		conscription: 'No',
		nuclearWeapons: 'Secret',
		chemicalWeapons: 'Secret',
		biologicalWeapons: 'No',
		currency: 'Esfalsan fallor',
		gdp: 1208174117040,
		industries: 'Information technology, consumer electronics, agriculture',
		oil: 'Produces oil',
		coal: 'Mines coal',
		lifeExpectancy: 81.8,
		mys: 12.8,
		eys: 16.1,
		GNIpc: 63199,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Used',
		torture: 'Illegal',
		capitalPunishment: 'Illegal',
		sameSexMarriage: 'Legal',
		prostitution: 'Legal and regulated',
		laneSplitting: 'Illegal',
		internetAccess: 'Yes',
		drugs: 'Certain substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Football',
		speedLimit: '125 km/h',
		drivingSide: 'Right',
		area: 65987
	}
};
