export const data = {
	'222': {
		name: 'Emerald-Denver',
		pretitle: 'United Kingdoms',
		flag: 'https://i.postimg.cc/Dzqrs3Rs/Union-Flag.png',
		formation: '1980',
		population: 42300000,
		birthright: 'Unconditional',
		languages: 'Cimbrian, Ludvillian, Colradian',
		governmentType: 'Unitary Constitutional Monarchy/Confederation',
		powerSource: 'Democracy',
		ideology: 'Socialist',
		legislature: {
			name: 'Congress',
			upper: 'Union Senate',
			lower: 'Union House Of Representatives'
		},
		militarySpending: 8,
		conscription: 'Yes, a minority of the age groups is drafted',
		nuclearWeapons: 'Inactive',
		chemicalWeapons: 'Inactive',
		biologicalWeapons: 'No',
		currency: 'Emeraldian Buck',
		gdp: 950546650000,
		industries: 'Cars, Planes, and Guns',
		oil: 'Does not produce oil',
		coal: 'Does not mine coal',
		lifeExpectancy: null,
		mys: null,
		eys: null,
		GNIpc: 23206,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Abolished',
		torture: 'Illegal',
		capitalPunishment: 'Legal',
		sameSexMarriage: 'Legal',
		prostitution: 'Illegal',
		laneSplitting: 'Illegal',
		internetAccess: 'Yes',
		drugs: 'Certain substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: '',
		speedLimit: '100 km/h',
		drivingSide: 'Right',
		area: 79301
	},
	'033': {
		name: 'Esfalsa',
		pretitle: '',
		flag: 'https://raw.githubusercontent.com/esfalsagov/esfalsa-graphics/main/flag%20of%20esfalsa.svg',
		formation: '1043',
		population: 18793005,
		birthright: 'Restrictive birthright',
		languages: 'Austral',
		governmentType: 'Unitary presidential directorial republic',
		powerSource: 'Democracy',
		ideology: 'Liberal',
		legislature: {
			name: 'Assembly',
			upper: '',
			lower: ''
		},
		militarySpending: 2.3,
		conscription: 'No',
		nuclearWeapons: 'Secret',
		chemicalWeapons: 'Secret',
		biologicalWeapons: 'No',
		currency: 'Esfalsan fallor',
		gdp: 1208174117040,
		industries: 'Information technology, consumer electronics, agriculture',
		oil: 'Produces oil',
		coal: 'Mines coal',
		lifeExpectancy: 81.8,
		mys: 12.8,
		eys: 16.1,
		GNIpc: 63199,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Used',
		torture: 'Illegal',
		capitalPunishment: 'Illegal',
		sameSexMarriage: 'Legal',
		prostitution: 'Legal and regulated',
		laneSplitting: 'Illegal',
		internetAccess: 'Yes',
		drugs: 'Certain substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Football',
		speedLimit: '125 km/h',
		drivingSide: 'Right',
		area: 65987
	},
	'209': {
		name: 'Spiras',
		pretitle: 'Democratic Peoples Socialist Federation',
		flag: 'https://i.postimg.cc/tT6h2kC1/flag-3.png',
		formation: '1986',
		population: 1900000,
		birthright: 'Unconditional',
		languages: 'Tarnian(Spirasian Speech)',
		governmentType: 'Federal Democratic Socialist Republic',
		powerSource: 'Democracy',
		ideology: 'Socialist',
		legislature: {
			name: 'Federal Council',
			upper: 'Senate',
			lower: 'Chamber Of Representatives'
		},
		militarySpending: 4,
		conscription: 'Yes, a minority of the age groups is drafted',
		nuclearWeapons: 'No',
		chemicalWeapons: 'Active',
		biologicalWeapons: 'No',
		currency: 'Spiran',
		gdp: 60450000000,
		industries: 'Eco-Products, Technology, Electronics ',
		oil: 'Does not produce oil',
		coal: 'Does not mine coal',
		lifeExpectancy: 83.8,
		mys: 13.2,
		eys: 13,
		GNIpc: 17.418,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Abolished',
		torture: 'Illegal',
		capitalPunishment: 'Illegal except under exceptional circumstances',
		sameSexMarriage: 'Legal',
		prostitution: 'Illegal',
		laneSplitting: 'No existing law',
		internetAccess: 'Yes',
		drugs: 'Illegal',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Track',
		speedLimit: 'No general speed limit',
		drivingSide: 'Left',
		area: 54177
	},
	'197': {
		name: 'Livana',
		pretitle: 'Confederation',
		flag: 'https://imgur.com/epEx3ry',
		formation: '1848',
		population: 6842052,
		birthright: 'Restrictive birthright',
		languages: 'Livonian',
		governmentType: 'Semi-Presidential Federal Republic',
		powerSource: 'Democracy',
		ideology: 'Social democratic',
		legislature: {
			name: 'Parliament of Livana',
			upper: 'College of Seers',
			lower: 'College of Representatives'
		},
		militarySpending: 2.3,
		conscription: 'Yes, a majority of the age groups is drafted',
		nuclearWeapons: 'No',
		chemicalWeapons: 'No',
		biologicalWeapons: 'No',
		currency: 'Fera',
		gdp: 244293896.47,
		industries: 'Manufacturing',
		oil: 'Produces oil',
		coal: 'Mines coal',
		lifeExpectancy: 83.2,
		mys: 10.4,
		eys: 12.5,
		GNIpc: 38800,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Used',
		torture: 'Illegal',
		capitalPunishment: 'Illegal except under exceptional circumstances',
		sameSexMarriage: 'Legal',
		prostitution: 'Legal (with restrictions)',
		laneSplitting: 'No existing law',
		internetAccess: 'Yes',
		drugs: 'Legal only for medicinal use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Illegal except in case of rape or danger to maternal life',
		sport: 'Football',
		speedLimit: '70km/h',
		drivingSide: 'Left',
		area: 11574
	},
	'147': {
		name: 'Rijykas',
		pretitle: 'the Roug’s Republik over',
		flag: 'https://i.imgur.com/RIYYhnJ.png',
		formation: '2002',
		population: 4016085,
		birthright: 'Unconditional',
		languages: 'Rijyki',
		governmentType: 'Parliamentary Presidential Revolutionary Republic',
		powerSource: 'Democracy',
		ideology: 'Conservative',
		legislature: {
			name: 'Rijyki Legislature',
			upper: 'Grande Treize',
			lower: 'House of Representatives'
		},
		militarySpending: 2.14,
		conscription: 'Yes, a minority of the age groups is drafted',
		nuclearWeapons: 'Active',
		chemicalWeapons: 'No',
		biologicalWeapons: 'Inactive',
		currency: 'Ў Uuras',
		gdp: 726823815000,
		industries: 'Agriculture, Health Products, Tourism',
		oil: 'Produces oil',
		coal: 'Does not mine coal',
		lifeExpectancy: 92.73,
		mys: 8.8,
		eys: 13.8,
		GNIpc: 16918,
		hateSpeech: 'No existing law',
		lifeImprisonment: 'Used',
		torture: 'Illegal',
		capitalPunishment: 'Illegal except under exceptional circumstances',
		sameSexMarriage: 'Legal',
		prostitution: 'Illegal',
		laneSplitting: 'No existing law',
		internetAccess: 'Yes',
		drugs: 'Legal only for medicinal use',
		healthcare: 'Yes',
		vaccination: 'Voluntary',
		abortion: 'Illegal except in case of rape or danger to maternal life',
		sport: 'Ice Hockey',
		speedLimit: '90 mph, though number varies.',
		drivingSide: 'Right',
		area: 9028
	},
	'099': {
		name: 'Berusturg',
		pretitle: 'Federational kingdom of',
		flag: 'https://www.nationstates.net/images/flags/uploads/berusturg__719991.png',
		formation: '1678',
		population: 78517387,
		birthright: 'Restrictive birthright',
		languages: 'Berusturgian',
		governmentType: 'Federal parliamentary semi-constitutional monarchy',
		powerSource: 'Democracy',
		ideology: 'Semi-Constitutional Monarchism',
		legislature: {
			name: 'Council',
			upper: '',
			lower: ''
		},
		militarySpending: 13.5,
		conscription: 'Yes, a minority of the age groups is drafted',
		nuclearWeapons: 'No',
		chemicalWeapons: 'No',
		biologicalWeapons: 'No',
		currency: '',
		gdp: 75054000000,
		industries: 'Retail, Service, Mining',
		oil: 'Mainly refines oil',
		coal: 'Mines coal',
		lifeExpectancy: 71.8,
		mys: 10.7,
		eys: 15.8,
		GNIpc: 15698,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Used',
		torture: 'Illegal',
		capitalPunishment: 'Illegal except under exceptional circumstances',
		sameSexMarriage: 'Legal',
		prostitution: 'Legal and regulated',
		laneSplitting: 'Legal',
		internetAccess: 'Yes',
		drugs: 'Certain substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Football, Skiing, Ice Hockey',
		speedLimit: 'up to 100 km/h in cities, up to 145 km/h in highways',
		drivingSide: 'Right',
		area: 198233
	},
	'098': {
		name: 'Eflad',
		pretitle: 'Technocractic Republic',
		flag: 'https://www.nationstates.net/images/flags/uploads/eflad__420169.png',
		formation: '1840',
		population: 56700000,
		birthright: 'Unconditional',
		languages: 'Austral, Eflæde',
		governmentType: 'Federal parliamentary republic',
		powerSource: 'Democracy',
		ideology:
			'Due to the new government there is a shift to a more liberal and social democratic society, so both',
		legislature: {
			name: '',
			upper: 'Sænat',
			lower: 'Federal Konsul'
		},
		militarySpending: 1.42,
		conscription: 'No, but it is being introduced',
		nuclearWeapons: 'No, but rights reserved',
		chemicalWeapons: 'No',
		biologicalWeapons: 'No',
		currency: 'Ippon',
		gdp: 2272000000000,
		industries: 'Semiconductors, Information Technology, Railway infrastructure, Tourism',
		oil: 'Does not produce oil',
		coal: 'Does not mine coal',
		lifeExpectancy: 79.5,
		mys: 13.2,
		eys: 15.1,
		GNIpc: 49638,
		hateSpeech: 'No existing law',
		lifeImprisonment: 'Abolished',
		torture: 'Illegal',
		capitalPunishment: 'Illegal',
		sameSexMarriage: 'Legal',
		prostitution: 'Legal and regulated',
		laneSplitting: 'Illegal',
		internetAccess: 'Yes',
		drugs: 'Most substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Voluntary',
		abortion: 'Always legal',
		sport: 'Tennis, Karate',
		speedLimit: '130 km/h',
		drivingSide: 'Right',
		area: 152827
	},
	'041': {
		name: 'Nicholas and Great Britain',
		pretitle: 'Republic',
		flag: 'https://cdn.discordapp.com/attachments/871887423452364850/947262340657717269/Flag_of_Great_Britain_17071800.svg.png',
		formation: '1908',
		population: 82090193,
		birthright: 'Restrictive birthright',
		languages: 'Austral',
		governmentType: 'Unitary one party republic under a totalitarian dictatorship',
		powerSource: 'Dictatorship',
		ideology: 'Nationalist',
		legislature: {
			name: 'House of Parliament',
			upper: '',
			lower: ''
		},
		militarySpending: 5.7,
		conscription: 'Yes, a majority of the age groups is drafted',
		nuclearWeapons: 'Secret',
		chemicalWeapons: 'Active',
		biologicalWeapons: 'Active',
		currency: 'NichoPound',
		gdp: 3025554000000,
		industries: 'Arms Manufacturing, Information, Retail',
		oil: 'Produces oil',
		coal: 'Mines coal',
		lifeExpectancy: 79.7,
		mys: 12.9,
		eys: 16.7,
		GNIpc: 38292,
		hateSpeech: 'Legal',
		lifeImprisonment: 'Used',
		torture: 'Legal',
		capitalPunishment: 'Legal',
		sameSexMarriage: 'Illegal',
		prostitution: 'Illegal',
		laneSplitting: 'No existing law',
		internetAccess: 'Yes',
		drugs: 'Legal only for medicinal use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Association Football',
		speedLimit: '70 mph',
		drivingSide: 'Left',
		area: 171459
	},
	'023': {
		name: 'Berusturg',
		pretitle: 'Federational kingdom of',
		flag: 'https://www.nationstates.net/images/flags/uploads/berusturg__719991.png',
		formation: '1678',
		population: 78517387,
		birthright: 'Restrictive birthright',
		languages: 'Berusturgian',
		governmentType: 'Federal parliamentary semi-constitutional monarchy',
		powerSource: 'Democracy',
		ideology: 'Semi-Constitutional Monarchism',
		legislature: {
			name: 'Council',
			upper: '',
			lower: ''
		},
		militarySpending: 13.5,
		conscription: 'Yes, a minority of the age groups is drafted',
		nuclearWeapons: 'No',
		chemicalWeapons: 'No',
		biologicalWeapons: 'No',
		currency: '',
		gdp: 75054000000,
		industries: 'Retail, Service, Mining',
		oil: 'Mainly refines oil',
		coal: 'Mines coal',
		lifeExpectancy: 71.8,
		mys: 10.7,
		eys: 15.8,
		GNIpc: 15698,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Used',
		torture: 'Illegal',
		capitalPunishment: 'Illegal except under exceptional circumstances',
		sameSexMarriage: 'Legal',
		prostitution: 'Legal and regulated',
		laneSplitting: 'Legal',
		internetAccess: 'Yes',
		drugs: 'Certain substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Football, Skiing, Ice Hockey',
		speedLimit: 'up to 100 km/h in cities, up to 145 km/h in highways',
		drivingSide: 'Right',
		area: 88315
	},
	'021': {
		name: 'Berusturg',
		pretitle: 'Federational kingdom of',
		flag: 'https://www.nationstates.net/images/flags/uploads/berusturg__719991.png',
		formation: '1678',
		population: 78517387,
		birthright: 'Restrictive birthright',
		languages: 'Berusturgian',
		governmentType: 'Federal parliamentary semi-constitutional monarchy',
		powerSource: 'Democracy',
		ideology: 'Semi-Constitutional Monarchism',
		legislature: {
			name: 'Council',
			upper: '',
			lower: ''
		},
		militarySpending: 13.5,
		conscription: 'Yes, a minority of the age groups is drafted',
		nuclearWeapons: 'No',
		chemicalWeapons: 'No',
		biologicalWeapons: 'No',
		currency: '',
		gdp: 75054000000,
		industries: 'Retail, Service, Mining',
		oil: 'Mainly refines oil',
		coal: 'Mines coal',
		lifeExpectancy: 71.8,
		mys: 10.7,
		eys: 15.8,
		GNIpc: 15698,
		hateSpeech: 'Illegal',
		lifeImprisonment: 'Used',
		torture: 'Illegal',
		capitalPunishment: 'Illegal except under exceptional circumstances',
		sameSexMarriage: 'Legal',
		prostitution: 'Legal and regulated',
		laneSplitting: 'Legal',
		internetAccess: 'Yes',
		drugs: 'Certain substances legal for recreational use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Football, Skiing, Ice Hockey',
		speedLimit: 'up to 100 km/h in cities, up to 145 km/h in highways',
		drivingSide: 'Right',
		area: 17806
	},
	'040': {
		name: 'Nicholas and Great Britain',
		pretitle: 'Republic',
		flag: 'https://cdn.discordapp.com/attachments/871887423452364850/947262340657717269/Flag_of_Great_Britain_17071800.svg.png',
		formation: '1908',
		population: 82090193,
		birthright: 'Restrictive birthright',
		languages: 'Austral',
		governmentType: 'Unitary one party republic under a totalitarian dictatorship',
		powerSource: 'Dictatorship',
		ideology: 'Nationalist',
		legislature: {
			name: 'House of Parliament',
			upper: '',
			lower: ''
		},
		militarySpending: 5.7,
		conscription: 'Yes, a majority of the age groups is drafted',
		nuclearWeapons: 'Secret',
		chemicalWeapons: 'Active',
		biologicalWeapons: 'Active',
		currency: 'NichoPound',
		gdp: 3025554000000,
		industries: 'Arms Manufacturing, Information, Retail',
		oil: 'Produces oil',
		coal: 'Mines coal',
		lifeExpectancy: 79.7,
		mys: 12.9,
		eys: 16.7,
		GNIpc: 38292,
		hateSpeech: 'Legal',
		lifeImprisonment: 'Used',
		torture: 'Legal',
		capitalPunishment: 'Legal',
		sameSexMarriage: 'Illegal',
		prostitution: 'Illegal',
		laneSplitting: 'No existing law',
		internetAccess: 'Yes',
		drugs: 'Legal only for medicinal use',
		healthcare: 'Yes',
		vaccination: 'Mandatory',
		abortion: 'Always legal',
		sport: 'Association Football',
		speedLimit: '70 mph',
		drivingSide: 'Left',
		area: 183705
	}
};
